# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76c77dba45be2227bed6de07bc44d22a66567f7749918572d95a368a242c0a2521b6b1a8089f6d5d145f42376917c691ff415d1433660b2619b8651817bf2264

test:
  secret_key_base: 27d33e7f62919c9c3805062ae209b710e2895562fb4ea742823936cf71a6824308c4412de5ce1e3b1191d973c52a2bb412077136e13ea4329782ce4b19c8a360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
